### PR TITLE
add INSERT IGNORE for MySQL

### PR DESCRIPTION
**Pull request by pavarnos**
For #105

### CODE REVIEW

**Comment by shadowhand** [comment]
Dunno what's up with Travis, the [build is fine][1].

[1]: https://travis-ci.org/github/shadowhand/latitude/builds/701576026

**Comment by shadowhand** [comment]
Released in version 4.2.0.

**Comment by pavarnos** [comment]
thank you for the super quick merge and release.
latitude has lean elegant code: a great example of how to do something quite complicated in a very tidy way.

**Comment by shadowhand** [comment]
@pavarnos thank you for the kind words. I tried very hard to make it elegant.

**Pull request merged**
